data = {
    0: {
        'PATH': '../img/other/peabullet.png',
        'IMAGE_INDEX_MAX': 0,
        'IMAGE_INDEX_CD': 0.0,
        'POSITION_CD': 0.008,
        'SUMMON_CD': -1,
        "SIZE": (33, 33),
        'SPEED': (5, 0),
        'CAN_LOOT': False,
        'PRICE': 0,
        'HP': 1,
        'ATT': 1,
    },
    1: {
        'PATH': '../img/zombie/0/%d.png',
        'IMAGE_INDEX_MAX': 15,
        'IMAGE_INDEX_CD': 0.2,
        'POSITION_CD': 0.2,
        'SUMMON_CD': -1,
        "SIZE": (100, 128),
        'SPEED': (-5, 0),
        'CAN_LOOT': False,
        'PRICE': 0,
        'HP': 5,
        'ATT': 1,
    },
    2: {
        'PATH': '../img/other/sunlight/%d.png',
        'IMAGE_INDEX_MAX': 30,
        'IMAGE_INDEX_CD': 0.02,
        'POSITION_CD': 0.05,
        'SUMMON_CD': -1,
        "SIZE": (80, 80),
        'SPEED': (0, 2),
        'CAN_LOOT': True,
        'PRICE': 50,
        'HP': 100000,
        'ATT': 0,
    },
    3: {
        'PATH': '../img/plant/sunflower/%d.png',
        'IMAGE_INDEX_MAX': 19,
        'IMAGE_INDEX_CD': 0.07,
        'POSITION_CD': 10000,
        'SUMMON_CD': 8,
        "SIZE": (128, 128),
        'SPEED': (0, 0),
        'CAN_LOOT': False,
        'PRICE': 50,
        'HP': 5,
        'ATT': 0,
    },
    4: {
        'PATH': '../img/plant/peashooter/%d.png',
        'IMAGE_INDEX_MAX': 15,
        'IMAGE_INDEX_CD': 0.15,
        'POSITION_CD': 10000,
        'SUMMON_CD': 2,
        "SIZE": (128, 128),
        'SPEED': (0, 0),
        'CAN_LOOT': False,
        'PRICE': 100,
        'HP': 5,
        'ATT': 0,
    },
}
